### ISSUE TITLE
Oridnals sent to wrong address.

### ISSUE THREAD

**Issue by Wahhab-Mirza** [secretkeylabs/xverse-roadmap#1]
![image](https://github.com/secretkeylabs/xverse-roadmap/assets/3167532/449e1f9c-bd44-4e5e-805c-675c7b9e7df3)
 

One day ago my ordinal transferred automatically to wrong address please help me retrieve it.Thanks

**Comment by GAD2511** [comment]
Hello, your ordinal can't be transferred to another address automatically. You can contact Xverse support for help
